version: '3.8'
services:
 podman-react-vite:
  image: poadman-react-prod-ima
  build: 
   dockerfile: Dockerfile.prod
  container_name: podman-react-prod-container
  environment:
    - VITE_TEST_VAR=${import.meta.env.VITE_TEST_VAR}
  ports:
    - "8080:80"
