version: '3.8'
services:
 podman-react-vite:
  image: poadman-react-ima
  build: 
   dockerfile: Dockerfile
  container_name: podman-react-container
  environment:
    - VITE_TEST_VAR=${import.meta.env.VITE_TEST_VAR}
  ports:
    - "8081:80"
